/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code401challenges;
import java.lang.*;
import java.util.Arrays;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

}



